# Generated by Django 2.2.4 on 2019-08-05 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tldr', models.TextField(max_length=200)),
                ('fb_link', models.TextField(blank=True)),
                ('article_text', models.TextField()),
                ('is_main_article', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('is_found', models.BooleanField(default=False)),
                ('is_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=25)),
                ('dog_description', models.TextField()),
                ('dog_picture', models.ImageField(default='default_dog.jpg', upload_to='dogs_pics')),
                ('dog_gallery', models.TextField(default='https://www.facebook.com/pg/stowarzyszenieMamGlos/photos/?tab=albums')),
                ('was_adopted', models.BooleanField(default=False)),
                ('added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=35)),
                ('employee_picture', models.ImageField(default='personImage.png', upload_to='employees_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='nazwa')),
                ('logo', models.ImageField(default='default_logo.jpg', upload_to='partners_pics')),
                ('thanks_link', models.TextField(default='https://www.facebook.com/stowarzyszenieMamGlos/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='articles_pics')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article')),
            ],
        ),
    ]
