# Generated by Django 2.2.4 on 2019-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_checked',
            field=models.BooleanField(default=False),
        ),
    ]
