# Generated by Django 2.2.4 on 2019-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_article_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename_str',
            field=models.CharField(default='plik', max_length=50),
        ),
    ]
